serenity {
  project.name = "UI + API Automation Portfolio"
  browser = "chrome"
}

webdriver {
  driver = chrome
}

chrome {

  switches = [

    "--incognito",
    "--disable-infobars",
    "--disable-notifications",
    "--disable-popup-blocking",
    "--disable-extensions",
    "--disable-gpu",
    "--disable-dev-shm-usage",
    "--no-sandbox",

    "--disable-features=InterestCohort,PrivacySandboxAdsAPIsOverride,AdsInterestGroups,AdTopics",
    "--disable-background-networking",
    "--disable-sync",
    "--metrics-recording-only",
    "--disable-default-apps"
  ]
}

rest {
  base.url = "https://automationexercise.com/api"

  logging = VERBOSE

  log {
    requests = true
    responses = true
  }
}